version: '3'
services:
  wechat-chatgpt:
    build: .
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./logs:/code/logs
      - ./wechat-shanyue.memory-card.json:/code/wechat-shanyue.memory-card.json
    restart: always